services:
  app:
    image: ${APP_IMAGE:-pm-backend:latest}
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
    container_name: pm-backend
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_EXTERNAL_PORT}:3214"
    networks:
      - pm-net

networks:
  pm-net:
    external: true
