@host = http://localhost:4000
@baseUrl = {{host}}/api
@adminEmail = admin@example.com
@adminPassword = password

### Health
GET {{host}}/health

### API Root
GET {{baseUrl}}

### Auth Ping
GET {{baseUrl}}/auth/ping

### Users Ping
GET {{baseUrl}}/users/ping

### Projects Ping
GET {{baseUrl}}/projects/ping

############################################################
# AUTH
############################################################

### Login (admin)
# @name loginAdmin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

### Capture access token from login
@adminAccessToken = {{loginAdmin.response.body.data.accessToken}}

### Refresh
# @name refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{}

############################################################
# AUTH - Invitation
############################################################

### Invite user (ADMIN)
# @name inviteUser
POST {{baseUrl}}/auth/invite
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "email": "tanaba1623@naprb.com",
  "role": "STAFF"
}


# http://localhost:3000/register?token=TOKEN_HERE
### Register via invite
POST {{baseUrl}}/auth/register-via-invite
Content-Type: application/json

{
  "token": "PASTE_TOKEN_HERE",
  "name": "Staff One",
  "password": "Staff@12345"
}

############################################################
# USERS
############################################################

### List users (ADMIN)
# @name listUsers
GET {{baseUrl}}/users?page=1&limit=10
Authorization: Bearer {{adminAccessToken}}

### Change role
PATCH {{baseUrl}}/users/REPLACE_USER_ID/role
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "role": "MANAGER"
}

### Change status
PATCH {{baseUrl}}/users/REPLACE_USER_ID/status
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "status": "INACTIVE"
}
